### ISSUE TITLE
Doesn't perform JNDI lookups

### ISSUE THREAD

**Issue by tristan957** [deavmi/dlog#1]
Hi Tristan,

I was reading the source code and realized that this isn't doing JNDI lookups like log4j. Can you add support for that? Thanks.

Definitely not a hacker btw.

**Comment by deavmi** [comment]
I will look into this. What I am thinking of is maybe taking arbitrary strings, writing them to a file, then calling `dlopen()` on them, getting a list of ELF symbols and trying my best to call of of them with the correct arguments after using `dlsym()`?

I think this will make for a great feature addition as it will allow TRULY modular logging with dynamic linking.

Also I might do this with HTTP, you think this is a good first issue? @tristan957
