### ISSUE TITLE
Permission to create DLog provider for SLF4D

### ISSUE THREAD

**Issue by andrewlalis** [deavmi/dlog#3]
Hi there! I've recently developed [SLF4D](https://github.com/andrewlalis/slf4d) which is an attempt to unify various logging frameworks under a central, simple interface. You can read more about it on the readme if you'd like, but the point is that it provides an interface and end-users can configure it to use a certain _provider_, that is, a concrete logger implementation like std.logger or vibe-d.logger, or in this case, DLog.

I'd like to try making an `slf4d-dlog` module which makes a configurable form of DLog available to plug into SLF4D, so that any project using SLF4D can use DLog as the underlying logging provider. Are you okay with this? Do you have any concerns or things I should know about if I do go forward with this?

**Comment by deavmi** [comment]
It sounds like a good idea. I am currently just busy re-working a few things to be a bit cleaner, hopefully by the end of this week I will be done with what needs to be done on the `ng` branch and then I can push a new version from which you can work with (I don't want you doing double the work because of a change I make very soon).

I'll keep this issue open as a discussion thread for our back-and-forth (hint, I love the idea :fire:  !)

**Comment by deavmi** [comment]
So yes, you do have my permission. But I'll let you know within a day or so when it is finalised so I can freeze it and update the docs and you can then work with that (also shoot any questions my way)!

**Comment by deavmi** [comment]
I am busy fixing things as I type, it shouldn't take me too much longer. I'll let you know the tag to use once done :)

**Comment by andrewlalis** [comment]
Alright, I've been playing around with stuff already, and you can find my implementation [here](https://github.com/andrewlalis/slf4d-dlog).

One thing I noticed is that your Logger class is intended for use locally (as in, thread-local), whereas SLF4D is designed such that it has a `shared` component that handles log messages generated from possibly many threads. In my sample implementation I do some casting magic to allow multi-threaded writing to your Logger:
```d
    public shared void handle(LogMessage msg) {
        synchronized(this.dlogLogger) {
            // remove the `shared` qualifier because we know it's safe to use unshared methods within this block.
            auto unsharedLogger = cast(dlog.Logger) this.dlogLogger;
            unsharedLogger.log3!(const(string))(
                msg.message,
                "",
                "",
                0,
                cast(string) msg.sourceContext.moduleName.dup,
                "",
                cast(string) msg.sourceContext.functionName.dup
            );
        }
    }
```

I'm guessing you want to keep your Logger class as-is without adding a bunch of shared qualifiers and mutexes to make it thread-safe, so at the moment I see this as a decent compromise. Do you have an opinion on it?

**Comment by deavmi** [comment]
Okay, the documentation on my website is not yet up-to-date but going ahead the tagged commit `v0.3.3` should be good-to-go and start working with integrating into SLF4D!

**Comment by deavmi** [comment]
> Alright, I've been playing around with stuff already, and you can find my implementation [here](https://github.com/andrewlalis/slf4d-dlog).
> 
> One thing I noticed is that your Logger class is intended for use locally (as in, thread-local), whereas SLF4D is designed such that it has a `shared` component that handles log messages generated from possibly many threads. In my sample implementation I do some casting magic to allow multi-threaded writing to your Logger:
> 
> ```d
>     public shared void handle(LogMessage msg) {
>         synchronized(this.dlogLogger) {
>             // remove the `shared` qualifier because we know it's safe to use unshared methods within this block.
>             auto unsharedLogger = cast(dlog.Logger) this.dlogLogger;
>             unsharedLogger.log3!(const(string))(
>                 msg.message,
>                 "",
>                 "",
>                 0,
>                 cast(string) msg.sourceContext.moduleName.dup,
>                 "",
>                 cast(string) msg.sourceContext.functionName.dup
>             );
>         }
>     }
> ```
> 
> I'm guessing you want to keep your Logger class as-is without adding a bunch of shared qualifiers and mutexes to make it thread-safe, so at the moment I see this as a decent compromise. Do you have an opinion on it?

This is a good compromise.

Yes, I prefer keeping `dlog` as simple as possible so I think the way you wrapped is there with the monitor/mutex should be good.

I'll probably eventually end up using your library in a project of mine in the future as effectively I presume you have it `shared` in the global data section (so no TLS) and hence have a singleton access which makes a lot of sense for efficiency reasons (especially when considering spawning multiple connection handler threads in a network-server logging case - so great idea you got there :)).

Related code being your process-wide/`shared`:

```
    public shared this(Level loggingLevel = Levels.INFO) {
        this.loggerFactory = new shared DefaultLoggerFactory(
            new shared DLogHandler(),
            loggingLevel
        );
    }
```

---

Excuse my late replies :)

**Comment by deavmi** [comment]
I have added a few things now, I recommend checking the re-hashed `Logger` class within `dlog/core.d`, there are now a good set of methods there, including the ability to set bare basics like the log level etc.

Just had to work around some meta-programming constraints (namely that a custom context and `T...` doesn't work all too well, so I made a compromise and added `logger.args`) but it should work now. I have run my unit tests for `v0.3.3` and everything runs as expected. (I will be testing the other features out throughout the day as I have a project where I extend `dlog` to do other things so I will be checking that out throughout the day to ensure the re-work works well when extensibility comes into play).

Afterwhich I really need to update the docs on my site now :laugh:

**Comment by deavmi** [comment]
Reminds me of the funny habbit I have, don't know what it is but for some reason I always use `__gshared` and an explicit `Mutex` (lock-n-unlock). When I could let the compiler do it for me with `shared` and `synchronized` (huh, I have weird habbits :laughing: )

**Comment by deavmi** [comment]
This shows the example capabilities (gogga): https://code.dlang.org/my_packages/gogga

However, I am still updating `gogga` to the latest version of `dlog` as there is more I want to add. But it's probably the most featureful example of what I hope to use `dlog` extensibility for (custom transforms etc).

If you have any questions let me know - I am free later today to help with integration questions/code! @andrewlalis

**Comment by andrewlalis** [comment]
Okay, I've got to get back to actual work now, but I've published an initial version on dub: https://code.dlang.org/packages/slf4d-dlog

Currently SLF4D's context information isn't as detailed as DLog's so the messages are missing the filename and line number and whatnot, but I'll be adding some more context to SLF4D soon.

**Comment by deavmi** [comment]
Awesome! I'll take a look soon!

Good luck!

**Comment by deavmi** [comment]
There isn't much state that could be raced too, so not sure if the lock really is required (anything being swapped out or in - which I don't think I have a lot of) would be atomic, however the __gshared is achieved with `shared`. Anyways, locks don't hurt - and in any case good practice in case I DO decide to have some sort of shared state.

Now I **really** have to get back to work :laughs:

**Comment by deavmi** [comment]
How's the progress been @andrewlalis ?

**Comment by andrewlalis** [comment]
Pretty good; If you check, I've got SLF4D to where I want it, and I don't expect any more breaking changes to the developer's interface, so the v1.0.0 of slf4d-dlog seems stable to use.

There are still some little bits of context which SLF4D doesn't collect, so those are provided as empty strings to the `logc` function from DLog.

The whole thing should be theoretically thread-safe though (but I can't make any performance promises), and I think it's ready to try out.

**Comment by deavmi** [comment]
Great to hear! Thanks for the update @andrewlalis - I'll take it for spin in the next week or so!

**Comment by deavmi** [comment]
Should I close this issue for now? I am always available for discussions so I can leave it open for that if so - let me know! :smile:

**Comment by andrewlalis** [comment]
Yep, I'll go ahead and close it.
